services:
  - type: web
    name: social-media-calendar-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.0.0

  - type: web
    name: social-media-calendar-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: social-media-calendar-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_CHANNEL_ID
        sync: false

databases:
  - name: social-media-calendar-db
    plan: starter